config/routes.rb
Rails.application.routes.draw do
  root 'epicenter#feed'

  get 'following' => 'epicenter#following'
  get 'followers' => 'epicenter#followers'

  get 'all_users' => 'epicenter#all_users'
  get 'retweet' => 'tweets#retweet'
  get 'tag_tweets' => 'epicenter#tag_tweets'
  get 'show_user' => 'epicenter#show_user'
  get 'now_following' => 'epicenter#now_following'
  get 'unfollow' => 'epicenter#unfollow'
  resources :tweets
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tweet_tags
  has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  has_many :tweet_tags
  has_many :tags, through: :tweet_tags

  before_validation on: :create do
    if self.retweet.nil?
      self.link_check
    end
  end

  validates :message, presence: true
  validates :message, length: { maximum: 140, too_long: "Max 140 characters" }, on: :create

  after_validation on: :create do
    if self.retweet.nil?
      self.apply_link
    end
  end

  serialize :link, Array

  # private

  def link_check
    if self.message.include?("http://") || self.message.include?("https://")
      truncated_message = self.message.split.map do |word|
        if word.include? "http"
          self.link.push(word)
          "#{word[0..20]}..."
        else
          word
        end
      end
      self.message = truncated_message.join(' ')
    end
  end

  def apply_link
    if self.message.include?("http://") || self.message.include?("https://")
      linked_message = self.message.split.map do |word|
        if word.include? "http"
          "<a href='#{self.link.shift}' target='_blank'>#{word}</a>"
        else
          word
        end
      end
      self.message = linked_message.join(' ')
    end
  end
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets

  mount_uploader :avatar, AvatarUploader

  validates :username, presence: true
  validates :username, uniqueness: true

  serialize :following, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :location, :avatar, :following])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :bio, :location, :avatar, :following])
  end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  before_action :authenticate_user!
  
  def tag_tweets
    @tag = Tag.find(params[:id])
  end

  def feed
    @tweet = Tweet.new
    tweet_ids = current_user.following
    tweet_ids.push(current_user.id)

    @following_tweets = Tweet.where(user_id: tweet_ids).order(created_at: :desc)
  end

  def show_user
    @user = User.find(params[:id])
  end

  def all_users
    @users = User.all
  end

  def now_following
    current_user.following.push(params[:id].to_i)
    current_user.save

    redirect_to show_user_path(id: params[:id])
  end

  def unfollow
    current_user.following.delete(params[:id].to_i)
    current_user.save

    redirect_to show_user_path(id: params[:id])
  end

  def following
    @user = User.find(params[:id])
    @users = User.where(id: @user.following)
  end

  def followers
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if user.following.include?(@user.id)
        @users.push(user)
      end
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!

  include TweetsHelper

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.order(created_at: :desc)
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  def retweet
    @tweet = Tweet.create(user_id: current_user.id, retweet: params[:tweet_id])
    redirect_to root_path
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.create(tweet_params)

    @tweet = get_tagged(@tweet)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id, :link)
    end

    def retweet_params
      params.require(:tweet_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def random_tweet
    user_id = User.where(bot: true).sample.id
    message = Faker::TvShows::TwinPeaks.quote
    Tweet.create!(message: message, user_id: user_id)
  end

  def profile_pic(user)
    if user.autopic != nil
      user.autopic
    elsif user.avatar.url != nil
      user.avatar.url
    else
      'default.png'
    end
  end

  def who_to_follow
    pick_three = (User.pluck(:id) - current_user.following).sample(3)
    User.where(id: pick_three)
  end
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
  def get_users_followers(selected_user)
    count = 0
    User.all.each do |user|
      if user.following.include? selected_user.id
        count += 1
      end
    end
    count
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def get_tagged(tweet)
    new_message = tweet.message.split.map do |word|
      if word[0] == '#'
        tag = if Tag.pluck(:phrase).include?(word.downcase)
          Tag.find_by(phrase: word.downcase)
        else
          Tag.create(phrase: word.downcase)
        end
        TweetTag.create(tweet_id: tweet.id, tag_id: tag.id)
        "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
      else
        word
      end
    end
    tweet.update(message: new_message.join(' '))
    return tweet
  end
end




message = "hello this is a #tweet"

new_message = message.split.map do |word|
  if word[0] == '#'
     "<a href='/tag_tweets?id=1'>#{word}</a>"
   else
    word
  end
end

p new_message.join(' ')

app/views/epicenter/_user_card.html.erb
<div class="user-card">
	<div></div>
	<div class="profile-info-container">
		<%= link_to show_user_path(id: user.id) do %>
			<%= image_tag profile_pic(user), size: 72, class: 'profile-pic' %>
		<% end %>
		<div class="profile-names-container">
			<div><strong><%= link_to user.name, show_user_path(id: user.id) %></strong></div>
			<div class="text-muted"><%= link_to "@#{user.username}", show_user_path(id: user.id), class: 'text-muted' %></div>
		</div>
		
		
		<% if user == current_user %>
			<div class="profile-stats-container text-muted">
				<div>
					<p>Tweets</p>
					<%= current_user.tweets.count %>
				</div>
				
				<%= link_to following_path(id: current_user.id) do %>
					<p>Following</p>
					<%= current_user.following.length %>
				<% end %>

				<%= link_to followers_path(id: current_user.id) do %>
					<p>Followers</p>
					<%= get_users_followers(current_user) %>
				<% end %>
				
			</div>
		<% else %>
			<p><%= user.bio %></p>
		<% end %>
	</div>
</div>

app/views/epicenter/_user_list.html.erb
<div class="row">
  <% @users.each do |user| %>
    <div class="col-md-3">
      <div class="well user-list-wells">
        <div class="row">
          <div class="col-md-6">
            <%= image_tag profile_pic(user), size: 76, class: 'profile-pic' %>
          </div>
          <div class="col-md-6">
            <p>
              <% if current_user.following.include?(user.id) %>
                <%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-primary", id: "unfollow_btn" %>
              <% else %>
                <% if current_user.id != user.id %>
                  <%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
                <% end %>
              <% end %>
            </p>
          </div>
        </div>
        <div class="row">
          <%= link_to show_user_path(id: user.id) do %>
            <h3><%= user.name %></h3>
            <p>@<%= user.username %></p>
          <% end %>
          <p>
            <%= user.bio %>
          </p>
        </div>
        <div class="row">
          <div class="profile-stats-container text-muted">
            <div>
              <p>Tweets</p>
              <%= user.tweets.count %>
            </div>
            
            <%= link_to following_path(id: user.id) do %>
              <p>Following</p>
              <%= user.following.length %>
            <% end %>

            <%= link_to followers_path(id: user.id) do %>
              <p>Followers</p>
              <%= get_users_followers(user) %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/epicenter/_who_to_follow.html.erb
<div class="who-to-follow-container">
	
	<h4>Who to follow</h4>

	<% who_to_follow.each do |user| %>
		<div class="info-container">
	      <%= image_tag profile_pic(user), size: 48, class: "profile-pic" %>
	      <div class="info-contents">
		      <strong><%= link_to user.name, show_user_path(id: user.id) %></strong>
		      <span class="check">✅</span> 
		      <span class="text-muted">
		        @<%= user.username %> </span><br>
		      <div class="btn btn-success">Follow</div>
	      </div>
	    </div>
	<% end %>	

</div>

app/views/epicenter/all_users.html.erb
<h1>All Users</h1>

<style>
	.show-users {
		display: flex;
		flex-wrap: wrap;
	}

	.show-users > div {
		margin: 12px;
	}

</style>
<div class="show-users">
	<% @users.each do |user| %>
		<%= render 'user_card', user: user %>
	<% end %>
</div>

app/views/epicenter/feed.html.erb
<% random_tweet %>

<div class="content-container">
	<div class="main-container">
		<div class="main-inner-container">
			<div class="tweet-box">
				<%= render 'tweets/form', tweet: @tweet %>
			</div>

			<div>
			    <% @following_tweets.each do |tweet| %>
			    	<% unless tweet.retweet.nil? %>
			    		<% retweet_user = tweet.user %>
			    		<% tweet = Tweet.find(tweet.retweet) %>
					<% end %>
			    	<%= render 'layouts/tweet_card', tweet: tweet, retweet_user: retweet_user %>
			    <% end %>
			</div>			
		</div>
	</div>

	<div class="dashboard-container">
		<div class="dashboard-left">
			<%= render 'user_card', user: current_user %>
		</div>
		
		<div class="dashboard-right">
			<%= render 'who_to_follow' %>
		</div>
	</div>
</div>

app/views/epicenter/followers.html.erb
<h1><%= @user.name %>'s follwers:</h1>
<%= render 'user_list' %>

app/views/epicenter/following.html.erb
<h1><%= @user.name %> is following:</h1>
<%= render 'user_list' %>

app/views/epicenter/now_following.html.erb
<h1>Epicenter#now_following</h1>
<p>Find me in app/views/epicenter/now_following.html.erb</p>

app/views/epicenter/show_user.html.erb
<h1>@<%= @user.username %>'s Profile & Tweets</h1>

<p><%= @user.name %></p>
<p><%= @user.location %></p>
<p><%= @user.bio %></p>

<div class="profile-stats-container text-muted">
	<div>
	  <p>Tweets</p>
	  <%= @user.tweets.count %>
	</div>

	<%= link_to following_path(id: @user.id) do %>
	  <p>Following</p>
	  <%= @user.following.length %>
	<% end %>

	<%= link_to followers_path(id: @user.id) do %>
	  <p>Followers</p>
	  <%= get_users_followers(@user) %>
	<% end %>
</div>
<p>
    <% if current_user.following.include?(@user.id) %>
        <%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-primary follow-button", id: 'unfollow_btn' %>
    <% else %>
        <% if current_user.id != @user.id %>
        <%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary follow-button" %>
    <% end %>
    <% end %>
</p>

<% @user.tweets.each do |tweet| %>
    <%= render 'layouts/tweet_card', tweet: tweet %>
<% end %>

app/views/epicenter/tag_tweets.html.erb
<h1><%= @tag.phrase %></h1>

<% @tag.tweets.order(created_at: :desc).each do |tweet| %>
	<%= render 'layouts/tweet_card', tweet: tweet %>
<% end %>

app/views/epicenter/unfollow.html.erb
<h1>Epicenter#unfollow</h1>
<p>Find me in app/views/epicenter/unfollow.html.erb</p>

app/views/layouts/_tweet_card.html.erb
<div class="tweet-container">
  <div class="tweet-content">
    <% unless retweet_user.nil? %>
      <div class="text-muted">
        ♺ <%= link_to retweet_user.name, show_user_path(id: retweet_user.id) %> retweeted
      </div>
    <% end %>

    <div class="tweet-heading">
      <%= image_tag profile_pic(tweet.user), size: 48, class: "profile-pic" %>
      <strong><%= link_to tweet.user.name, show_user_path(id: tweet.user.id) %></strong>
      <span class="check">✅</span> 
      <span class="text-muted">
        @<%= tweet.user.username %> 
        • 
        <%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 86400 %>
        <%= tweet.created_at.strftime('%b %e') if Time.now - tweet.created_at >= 86400 %>

      </span>
    </div>
    <p><%= tweet.message.html_safe %></p>
    <p><%= link_to '♻︎', retweet_path(tweet_id: tweet.id) %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Home", root_path, class: "navbar-brand" %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "Compose New Tweet", new_tweet_path %></li>
            <li><%= link_to 'All Tweets', tweets_path %></li>
            <li><%= link_to 'All Users', all_users_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <%= image_tag profile_pic(current_user), size: 25, class: 'profile-pic' %>
                  @<%= current_user.username %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="page-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :message, placeholder: "What's happening?", class: 'tweet-input' %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit 'Tweet', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<% random_tweet %>

<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message %></td>
        <td><%= link_to tweet.user.username, show_user_path(id: tweet.user.id) %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'layouts/tweet_card', tweet: @tweet %>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>